### ISSUE TITLE
Author, please help me！！！！！

### ISSUE THREAD

**Issue by sorrowfullys** [ravinrabbid/DonCon2040#4]
![微信图片_20240305030249](https://github.com/ravinrabbid/DonCon2040/assets/157891857/03d52aaa-5f01-481d-9043-2baa6c9ccdd9)
![微信图片_20240305030241](https://github.com/ravinrabbid/DonCon2040/assets/157891857/5f2dcb0c-63d6-4a52-b080-0aaaca482137)

**Comment by sorrowfullys** [comment]
HELLO,my english not good,hope you can understand
i am make it,doncon io and doncon pad，but ，end ，the don is ok.80 can to use and very sensitive ,but the ka is not ok after on the Arcade drum skin,if 2 is Automatic triggering, set 3 also need a certain amount of force to trigger,so, How should I debug code,.Make the ka more sensitive, thank you very much, i really need your help, please

**Comment by ravinrabbid** [comment]
Hi,

happy to see someone attempting to build this project :)

Getting the sensitivity right is not easy and I'm also not entirely happy with my build yet. From my experience, the largest influence is the construction of the drum itself. I don't know your build and I sadly have no access to a arcade drum skin to see how it behaves.

I can give you some general tips which helped me to increase sensitivity:

- Make sure all pads have the same height and are level. There should be no gap between the drum skin and the pads. I used paper washers for leveling the individual pads.
- Sensors need to be attached as firmly as possible to the pads. I used some custom build metal brackets.
- You can also try to attach the sensors closer to the to (where you hit the drum)

You can also try to increase the amplifier gain only for the KAs, but this might not solve the actual issue.

**Comment by sorrowfullys** [comment]
感谢您给的回答，为了提高咔的灵敏度，我做了以下改进方案，确实如您所说，1，我改变了，咔传播的介质，调整了咔的位置，使之相同力度产生更大的数值，2，我给做的木板边缘做了倒角处理，使之更贴合橡胶，3，我改变了2个咔的前端电路，把2个1兆欧的电阻换成了100k，试图让咔产生的信号加大，如您所说，您说的建议我都尝试过，但是假如感应器和木板之间像官机加了一层铁板的话，哪怕上面情况都调整了，触发力度仍然不够，不加铁板，阀值也必须设置个位数才行，太极限了，咚是贴木板的，咔是贴铁板的，官机就是这样，所以我想让您调试下代码，告诉我调哪里可以提升咔的灵敏度，或者告诉我如何调整咔的前端电路，阻值应该如何更换大小，才能更有效的提升咔产生的数值，非常感谢

**Comment by sorrowfullys** [comment]
Thank you for your answer. 
In order to improve the consistency of the click, 
I made the following improvements to the plan. 
It is exactly as you said, 
1. I changed the medium of click propagation and adjusted the position of the click so that the same intensity can produce greater The value, 
2, I chamfered the edge of the wooden board to make it fit the rubber better, 
3, I made 2 front-end changes to the circuit, and replaced the two 1M欧 with 100k, Trying to adjust the signal strength generated by the card, 
as you said, 
but I have tried everything you said. Assuming that a layer of iron plate is added between the sensor and the wooden board like the official machine, 
the above conditions have been adjusted, 
and the triggering strength It’s still not enough. 
If you don’t add an iron plate, the threshold must also be adjusted. It’s too extreme. The dong is attached to the wooden board, and the click is attached to the iron plate. This is how the official machine is, so I want you to debug the code. Tell me where to adjust to improve the click sound, or tell me how to adjust the pre-circuit of the click, and how to change the resistance value to more effectively improve the value generated by the click. Thank you very much.

**Comment by sorrowfullys** [comment]
Thankyou very much and i am finished 
ka is ok，problem is The size of the board

**Comment by ravinrabbid** [comment]
Sorry for the delayed answer, I've been busy the last few days.
Nice to hear that you got it working, I will close this issue then.

I you like to share some details which could help other people, feel free to use the 'Discussions' section.
